name = "MCMCBenchmarks"
uuid = "72ce6e51-3f7f-5ebd-8e88-b86aa3e31c30"
authors = ["Christopher R. Fisher, Rob J. Goedman"]
version = "0.7.3"

[deps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCDiagnostics = "6e857e4b-079a-58c4-aeab-bc2670384359"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
AdvancedHMC = "^0.2"
CSV = "^0.5, 0.6, 0.7, 0.8"
CmdStan = "^5.2, 6.0"
DataFrames = "0.21.0, 0.22, 1.1"
Distributions = "^0.21, 0.22, 0.23, 0.25"
DynamicHMC = "^2.1, 3.1"
FillArrays = "^0.8, 0.10, 0.11, 0.12"
ForwardDiff = "^0.10"
LogDensityProblems = "^0.9, 0.10"
MCMCChains = "^3.0, 4.0"
MCMCDiagnostics = "^0.3"
Parameters = "^0.12"
Reexport = "^0.2, 1.0"
Requires = "1.0"
Revise = "^2.2, 3.1"
SpecialFunctions = "^0.8, 0.9, 0.10"
StatsPlots = "^0.12, 0.13, 0.14"
Tracker = "^0.2"
TransformVariables = "^0.3, 0.4"
Turing = "^0.9, 0.10, 0.11, 0.12.0, 0.13, 0.14, 0.15, 0.16"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
